#' Title with Subtitle
#'
#' This function modifies the title and adds in a subtitle to a plot generated by ggplot2.
#' @param title Title of plot.
#' @param subtitle Subtitle of plot
#' @keywords ggplot2, title, subtitle
#' @export
#' @examples
#' ggplot(dat, aes(x = x, y = y)) + goem_point() +
#' title_with_subtitle(title = "The Title of the Plot", subtitle = "The Subtitle that explains more detail of the Title")
title_with_subtitle = function(title, subtitle = "") {
  ggtitle(bquote(atop(.(title), atop(.(subtitle)))))
}