# setwd("C:/Users/bpk3381/Documents/LGRiskAssessPhaseIIModeling/MbrLvlModeling")
# 
# lg_mbrlvl_train <- read.csv("LG_MBR_LVL_TRAIN.csv", header = TRUE)
# head(lg_mbrlvl_train)
# 
# #some scatter plots;
# with(lg_mbrlvl_train, plot(cmpl_tot_med_paid_amt, devel_silver_hcc_score) )
# 
# with(lg_mbrlvl_train[lg_mbrlvl_train$cmpl_tot_med_paid_amt>0, ], plot(cmpl_tot_med_paid_amt, devel_silver_hcc_score) )


library(gbm)

gbm_model <- gbm(formula = devel_silver_hcc_score ~
      #?cobra_status_ind   +
      humana_employ_ind	 +
      subs_humana_employ_ind	 +
      retire_ind	 +
      #subs_retire_ind	 +
      #rx_eligible_ind	 +
      smoke_ind_y	 +
      smoke_ind_u	 +
      smoke_ind_n	 +
      student_ind	 +
      no_prior_med_cov_ind	 +
      out_of_area_ind	 +
      AL_AGEINMTHS	 +
      AL_APT_A	 +
      AL_APT_B	 +
      AL_APT_C	 +
      AL_APT_N	 +
      AL_APT_P	 +
      AL_APT_S	 +
      AL_APT_T	 +
      AL_ATV_Y	 +
      AL_Age_ge_65	 +
      AL_BAVGDOLL	 +
      AL_BAVGOFDL	 +
      AL_BAVGONDL	 +
      AL_BBDN_Y	 +
      AL_BC_M	 +
      AL_BC_Y	 +
      AL_BHGHSCAL	 +
      AL_BLOWSCAL	 +
      AL_BMIDSCAL	 +
      AL_BOAT_Y	 +
      AL_BOFDOLLR	 +
      AL_BOFORDER	 +
      AL_BONDOLLR	 +
      AL_BONORDER	 +
      AL_BTOTLDOL	 +
      AL_BTOTLORD	 +
      AL_BUYER_Y	 +
      AL_C210APVT	 +
      AL_C210B200	 +
      AL_C210BPVT	 +
      AL_C210M200	 +
      AL_CALAGE_rc	 +
      AL_CAT_BUYER	 +
      AL_CBLU	 +
      AL_CBSA	 +
      AL_CCIP	 +
      AL_CCW_Y	 +
      AL_CEBI	 +
      AL_CE_Y	 +
      AL_CFCC_F2	 +
      AL_CFCC_F3	 +
      AL_CFCC_F4	 +
      AL_CFCC_F5	 +
      AL_CFCC_F6	 +
      AL_CFCC_G1	 +
      AL_CFCC_G4	 +
      AL_CFCC_G5	 +
      AL_CFCC_G6	 +
      AL_CFCC_N1	 +
      AL_CFCC_N2	 +
      AL_CGQS	 +
      AL_CHMI	 +
      AL_CHVA	 +
      AL_CMYS_2	 +
      AL_CMYS_3	 +
      AL_CMYS_4	 +
      AL_CMYS_5	 +
      AL_CMYS_6	 +
      AL_COLLEGE_Y	 +
      AL_CONSHOP_Y	 +
      AL_CO_Y	 +
      AL_CPDC	 +
      AL_CP_F	 +
      AL_CP_M	 +
      AL_CSAG_rc	 +
      AL_CSR_Y	 +
      AL_CWHT	 +
      AL_DART_Y	 +
      AL_DAUT_Y	 +
      AL_DBBL_Y	 +
      AL_DBIC_Y	 +
      AL_DBKR_Y	 +
      AL_DBOT_Y	 +
      AL_DBVD_Y	 +
      AL_DCAT_Y	 +
      AL_DCDP_Y	 +
      AL_DCHR_Y	 +
      AL_DCMP_Y	 +
      AL_DCOL_Y	 +
      AL_DCRF_Y	 +
      AL_DCRR_Y	 +
      AL_DCTV_Y	 +
      AL_DCUL_Y	 +
      AL_DCUR_Y	 +
      AL_DCVC_Y	 +
      AL_DDOG_Y	 +
      AL_DDWC_Y	 +
      AL_DEID_10_Ir	 +
      AL_DEID_16_Scot	 +
      AL_DEID_58_AFRAm	 +
      AL_DEID_6_EngBrit	 +
      AL_DEID_8_Ger	 +
      AL_DEID_9_His	 +
      AL_DEID_OTHR	 +
      AL_DELE_Y	 +
      AL_DFAS_Y	 +
      AL_DFIT_Y	 +
      AL_DFRN_Y	 +
      AL_DFSH_Y	 +
      AL_DFTV_Y	 +
      AL_DGAR_Y	 +
      AL_DGCH_Y	 +
      AL_DGLF_Y	 +
      AL_DGMB_Y	 +
      AL_DGRM_Y	 +
      AL_DHER_Y	 +
      AL_DHH_Y	 +
      AL_DHLH_Y	 +
      AL_DHNT_Y	 +
      AL_DHPC_Y	 +
      AL_DHPL_Y	 +
      AL_DIMP_Y	 +
      AL_DMBY_Y	 +
      AL_DMCI_Y	 +
      AL_DMNY_Y	 +
      AL_DMVT_Y	 +
      AL_DNDL_Y	 +
      AL_DNRM	 +
      AL_DNRM_1	 +
      AL_DNRM_2	 +
      AL_DNRM_3	 +
      AL_DNRM_4	 +
      AL_DNRM_5	 +
      AL_DNRM_6	 +
      AL_DNRM_7	 +
      AL_DNRM_8	 +
      AL_DNRM_9	 +
      AL_DNRM_10	 +
      AL_DN_M	 +
      AL_DN_Y	 +
      AL_DPBT_Y	 +
      AL_DPET_Y	 +
      AL_DPIC_Y	 +
      AL_DRCD_Y	 +
      AL_DRES_Y	 +
      AL_DRUN_Y	 +
      AL_DRVL_Y	 +
      AL_DSAL_Y	 +
      AL_DSCC_Y	 +
      AL_DSEW_Y	 +
      AL_DSFN_Y	 +
      AL_DSSK_Y	 +
      AL_DSTK_Y	 +
      AL_DSTV_Y	 +
      AL_DSWP_Y	 +
      AL_DTEC_Y	 +
      AL_DTEN_Y	 +
      AL_DTVL_Y	 +
      AL_DUALINCM	 +
      AL_DUALINCM_0	 +
      AL_DUALINCM_1	 +
      AL_DUALINCM_2	 +
      AL_DUALINCM_3	 +
      AL_DUALINCM_4	 +
      AL_DUALINCM_5	 +
      AL_DUALINCM_6	 +
      AL_DUALINCM_7	 +
      AL_DUALINCM_8	 +
      AL_DUALINCM_9	 +
      AL_DVDG_Y	 +
      AL_DVDR_Y	 +
      AL_DWELLING_AGE	 +
      AL_DWIN_Y	 +
      AL_DWKS_Y	 +
      AL_DWLD_Y	 +
      AL_DWLK_Y	 +
      AL_DaysSinceLastOnLineOrder	 +
      AL_DaysSinceLastRetailOrder	 +
      AL_DaysSinceLastOffLineOrder	 +
      AL_EMDM_Y	 +
      AL_ESTINC19_A	 +
      AL_ESTINC19_B	 +
      AL_ESTINC19_C	 +
      AL_ESTINC19_D	 +
      AL_ESTINC19_E	 +
      AL_ESTINC19_F	 +
      AL_ESTINC19_G	 +
      AL_ESTINC19_H	 +
      AL_ESTINC19_I	 +
      AL_ESTINC19_J	 +
      AL_ESTINC19_K	 +
      AL_ESTINC19_L	 +
      AL_ESTINC19_M	 +
      AL_ESTINC19_N	 +
      AL_ESTINC19_O	 +
      AL_ESTINC19_RC	 +
      AL_FAMP_B	 +
      AL_FAMP_C	 +
      AL_FAMP_F	 +
      AL_FAMP_G	 +
      AL_FAMP_H	 +
      AL_FAMP_M	 +
      AL_FAMP_P	 +
      AL_FAMP_S	 +
      AL_FAMP_W	 +
      AL_FINB_Y	 +
      AL_FINC_Y	 +
      AL_FINI_Y	 +
      AL_FURN_Y	 +
      AL_GEND_F	 +
      AL_GEND_M	 +
      AL_GENERS_01s_StrapS	 +
      AL_GENERS_02s_RR	 +
      AL_GENERS_03s_BloomB	 +
      AL_GENERS_04s_RRent	 +
      AL_GENERS_05s_MinM	 +
      AL_GENERS_06s_InIntel	 +
      AL_GENERS_07s_FamF	 +
      AL_GENERS_09s_UUC	 +
      AL_GENERS_10s_BB	 +
      AL_GENERS_11l_STT	 +
      AL_GENERS_12l_GnG	 +
      AL_GENERS_13l_STS	 +
      AL_GENERS_14l_MM	 +
      AL_GENERS_15l_AmB	 +
      AL_GENERS_16l_UMix	 +
      AL_GENERS_17l_UrbanB	 +
      AL_GENERS_18l_CreditC	 +
      AL_GENERS_19l_BCS	 +
      AL_GENERS_20l_SettS	 +
      AL_GENERS_21l_ClassR	 +
      AL_GENERS_22l_AllAmO	 +
      AL_GENERS_23t_RuralO	 +
      AL_GENERS_24t_FamTran	 +
      AL_GENERS_25t_UrOut	 +
      AL_GENERS_26t_SubM	 +
      AL_GENERS_27t_MInf	 +
      AL_GENERS_28t_WW	 +
      AL_GENERS_29t_USoph	 +
      AL_GENERS_30t_SubStr	 +
      AL_GENERS_31t_ENC	 +
      AL_GENERS_32t_AFUC	 +
      AL_GENERS_33t_BCB	 +
      AL_GENERS_34t_UStrug	 +
      AL_GENERS_35x_LExtFam	 +
      AL_GENERS_36x_UrbSing	 +
      AL_GENERS_37x_EstSettIn	 +
      AL_GENERS_38x_RuralBMIt	 +
      AL_GENERS_39x_MWChD	 +
      AL_GENERS_40x_StrugSub	 +
      AL_GENERS_41x_EthDUrB	 +
      AL_GENERS_42x_MovStC	 +
      AL_GENERS_43x_BigBBC	 +
      AL_GENERS_44y_ESecCSt	 +
      AL_GENERS_45y_YSMob	 +
      AL_GENERS_46y_SupHSD	 +
      AL_GENERS_47y_StUpsC	 +
      AL_GENERS_48y_ParGo	 +
      AL_GENERS_49y_LOffMD	 +
      AL_GENERS_50y_ChrRes	 +
      AL_GENERS_51y_YSinglCY	 +
      AL_GENERS_52y_FamFirst	 +
      AL_HHCOMP_A	 +
      AL_HHCOMP_B	 +
      AL_HHCOMP_C	 +
      AL_HHCOMP_D	 +
      AL_HHCOMP_E	 +
      AL_HHCOMP_F	 +
      AL_HHCOMP_G	 +
      AL_HHCOMP_H	 +
      AL_HHCOMP_I	 +
      AL_HHCOMP_J	 +
      AL_HHCOMP_K	 +
      AL_HHCOMP_L	 +
      AL_HHID	 +
      AL_HIRI	 +
      AL_HIRI_0	 +
      AL_HIRI_1	 +
      AL_HIRI_2	 +
      AL_HIRI_3	 +
      AL_HIRI_4	 +
      AL_HIRI_5	 +
      AL_HIRI_6	 +
      AL_HIRI_7	 +
      AL_HIRI_8	 +
      AL_HIRI_9	 +
      AL_HIR_Y	 +
      AL_HOMI_Y	 +
      AL_HOMO_Y	 +
      AL_HOMSTAT_P	 +
      AL_HOMSTAT_R	 +
      AL_HOMSTAT_T	 +
      AL_HOMSTAT_U	 +
      AL_HOMSTAT_Y	 +
      AL_HOPLUS_P	 +
      AL_HOPLUS_Y	 +
      AL_HTFH_Y	 +
      AL_HVZIP4	 +
      AL_IDC_Y	 +
      AL_ILOR	 +
      AL_INAH	 +
      AL_INPH	 +
      AL_IOHO_Y	 +
      AL_IOLA_Y	 +
      AL_IOLP_Y	 +
      AL_IOMA_Y	 +
      AL_IOMG_Y	 +
      AL_IOOW_Y	 +
      AL_IOPT_Y	 +
      AL_IORE_Y	 +
      AL_IOSA_Y	 +
      AL_IOSE_Y	 +
      AL_IOST_Y	 +
      AL_IOTR_Y	 +
      AL_IPAE_Y	 +
      AL_IPDI_Y	 +
      AL_IPOT_Y	 +
      AL_IPSR_Y	 +
      AL_IPVM_Y	 +
      AL_IRAE_Y	 +
      AL_IRDI_Y	 +
      AL_IROT_Y	 +
      AL_IRSR_Y	 +
      AL_IRVM_Y	 +
      AL_IncPerAdult	 +
      AL_LAAI_Y	 +
      AL_LAAL_Y	 +
      AL_LAAM_Y	 +
      AL_LAAR_Y	 +
      AL_LAAS_Y	 +
      AL_LABE_Y	 +
      AL_LACE_Y	 +
      AL_LACN_Y	 +
      AL_LACO_Y	 +
      AL_LADY_Y	 +
      AL_LAEA_Y	 +
      AL_LAFF_Y	 +
      AL_LAFT_Y	 +
      AL_LAIN_Y	 +
      AL_LAIS_Y	 +
      AL_LANG_6_English	 +
      AL_LANG_9_HisSp	 +
      AL_LANG_OTHR	 +
      AL_LANL_Y	 +
      AL_LAOP_Y	 +
      AL_LAOR_Y	 +
      AL_LAPL_Y	 +
      AL_LARO_Y	 +
      AL_LART_Y	 +
      AL_LASF_Y	 +
      AL_LASI_Y	 +
      AL_LASO_Y	 +
      AL_LASS_Y	 +
      AL_LAT	 +
      AL_LATL_Y	 +
      AL_LATR_Y	 +
      AL_LATS_Y	 +
      AL_LAYC_Y	 +
      AL_LNG	 +
      AL_LOWD_Y	 +
      AL_LWCM02	 +
      AL_LWCM03	 +
      AL_LWCM04	 +
      AL_LWCM05	 +
      AL_LWCM06	 +
      AL_LWCM07	 +
      AL_LWCM08	 +
      AL_LWCM09	 +
      AL_LWCM10	 +
      AL_LWCM11	 +
      AL_LWCM12	 +
      AL_LWCM02rrnk	 +
      AL_LWCM03rrnk	 +
      AL_LWCM04rrnk	 +
      AL_LWCM05rrnk	 +
      AL_LWCM06rrnk	 +
      AL_LWCM07rrnk	 +
      AL_LWCM08rrnk	 +
      AL_LWCM09rrnk	 +
      AL_LWCM10rrnk	 +
      AL_LWCM11rrnk	 +
      AL_LWCM12rrnk	 +
      AL_LiveWell_1	 +
      AL_LiveWell_2	 +
      AL_LiveWell_3	 +
      AL_LiveWell_4	 +
      AL_LiveWell_5	 +
      AL_LiveWell_6	 +
      AL_MB2G_1_Express	 +
      AL_MB2G_2_Driven	 +
      AL_MB2G_3_ACap	 +
      AL_MB2G_4_RS	 +
      AL_MB2G_5_DTE	 +
      AL_MB2G_6_Soph	 +
      AL_MB2G_7_MT	 +
      AL_MB2G_8_Dev	 +
      AL_MB2S_10_RSRel	 +
      AL_MB2S_11_RSRig	 +
      AL_MB2S_12_RSRes	 +
      AL_MB2S_13_DTEDet	 +
      AL_MB2S_14_DTEDis	 +
      AL_MB2S_15_DTEDar	 +
      AL_MB2S_16_SSD	 +
      AL_MB2S_17_SSy	 +
      AL_MB2S_18_SSyn	 +
      AL_MB2S_19_MTwM	 +
      AL_MB2S_1_ExElus	 +
      AL_MB2S_20_MTwMet	 +
      AL_MB2S_21_MTwMot	 +
      AL_MB2S_22_DDis	 +
      AL_MB2S_23_DDisc	 +
      AL_MB2S_24_DDeft	 +
      AL_MB2S_2_ExEval	 +
      AL_MB2S_3_ExExub	 +
      AL_MB2S_4_DDel	 +
      AL_MB2S_5_DDil	 +
      AL_MB2S_6_DDy	 +
      AL_MB2S_7_ACA	 +
      AL_MB2S_8_ACApp	 +
      AL_MB2S_9_ACAtt	 +
      AL_MEDA	 +
      AL_MEMW_Y	 +
      AL_MISC_Y	 +
      AL_MOBPLUS_M	 +
      AL_MOBPLUS_P	 +
      AL_MOBPLUS_S	 +
      AL_MORI_Y	 +
      AL_MR_M	 +
      AL_MR_Y	 +
      AL_MSR_Y	 +
      AL_M_CHMI	 +
      AL_N1819_Y	 +
      AL_N2029_Y	 +
      AL_N2AUTO	 +
      AL_N2MAH	 +
      AL_N2MOB	 +
      AL_N2NCY_A	 +
      AL_N2NCY_B	 +
      AL_N2NCY_C	 +
      AL_N2NCY_D	 +
      AL_N2PBL	 +
      AL_N2PDV	 +
      AL_N2PHI	 +
      AL_N2PMI	 +
      AL_N2PMR	 +
      AL_N2PMV	 +
      AL_N2POO	 +
      AL_N2PSB	 +
      AL_N2PSU	 +
      AL_N2PWC	 +
      AL_N2PWH	 +
      AL_N3039_Y	 +
      AL_N4049_Y	 +
      AL_N5059_Y	 +
      AL_N6064_Y	 +
      AL_N65P_Y	 +
      AL_NAH19	 +
      AL_NDAD_Y	 +
      AL_NDBD_Y	 +
      AL_NDCD_Y	 +
      AL_NDDD_Y	 +
      AL_NDFD_Y	 +
      AL_NDGD_Y	 +
      AL_NDOD_Y	 +
      AL_NDYD_Y	 +
      AL_NETW19_A	 +
      AL_NETW19_B	 +
      AL_NETW19_C	 +
      AL_NETW19_D	 +
      AL_NETW19_E	 +
      AL_NETW19_F	 +
      AL_NETW19_G	 +
      AL_NETW19_H	 +
      AL_NETW19_I	 +
      AL_NETW19_J	 +
      AL_NETW19_K	 +
      AL_NETW19_L	 +
      AL_NETW19_M	 +
      AL_NETW19_N	 +
      AL_NETW19_RC	 +
      AL_NOC	 +
      AL_NOC19	 +
      AL_NPH19	 +
      AL_NTWPERYR	 +
      AL_NWPerAdult	 +
      AL_OABIGTLL_Y	 +
      AL_OACHILD_Y	 +
      AL_OAGEN_Y	 +
      AL_OAMEN_Y	 +
      AL_OANOGEN_Y	 +
      AL_OAPETITE_Y	 +
      AL_OAPLUS_Y	 +
      AL_OARTS_Y	 +
      AL_OATEEN_Y	 +
      AL_OAUTO_Y	 +
      AL_OAWOMEN_Y	 +
      AL_OBEAUTY_Y	 +
      AL_OBOOKS_Y	 +
      AL_OCHILDPR_Y	 +
      AL_OCOLLECT_Y	 +
      AL_OCOMPHMO_Y	 +
      AL_OCRAFTS_Y	 +
      AL_OC_10_PTec	 +
      AL_OC_13_Teach	 +
      AL_OC_20_Adm	 +
      AL_OC_21_Manag	 +
      AL_OC_22_Propr	 +
      AL_OC_30_Sales	 +
      AL_OC_40_Cler	 +
      AL_OC_50_Craft	 +
      AL_OC_52_Oper	 +
      AL_OC_61_UNSK	 +
      AL_OC_62_SerW	 +
      AL_OC_70_Mil	 +
      AL_OC_80_Stud	 +
      AL_OC_90_Ret	 +
      AL_OC_91_HWf	 +
      AL_OC_93_NCD	 +
      AL_OELECTNC_Y	 +
      AL_OFFLINE_BUYER	 +
      AL_OFOOD_Y	 +
      AL_OFURNITR_Y	 +
      AL_OGARDEN_Y	 +
      AL_OGEN_Y	 +
      AL_OGIFT_Y	 +
      AL_OHEALTH_Y	 +
      AL_OHMCARE_Y	 +
      AL_OHMFURN_Y	 +
      AL_OHOLIDAY_Y	 +
      AL_OHSWARE_Y	 +
      AL_OILC_Y	 +
      AL_OJEWELRY_Y	 +
      AL_OLINENS_Y	 +
      AL_OMUSIC_Y	 +
      AL_ONLA_Y	 +
      AL_ONLINE_BUYER	 +
      AL_ONOVEL_Y	 +
      AL_OOTHER_Y	 +
      AL_OPERCARE_Y	 +
      AL_OPETS_Y	 +
      AL_OPHOTO_Y	 +
      AL_OSPECFD_Y	 +
      AL_OSPECGFT_Y	 +
      AL_OSPORTS_Y	 +
      AL_OSTATION_Y	 +
      AL_OTRAVEL_Y	 +
      AL_OVIDDVD_Y	 +
      AL_PART_D	 +
      AL_PART_I	 +
      AL_PART_R	 +
      AL_PDPE	 +
      AL_PFFS	 +
      AL_PILOTS_Y	 +
      AL_POC19_P	 +
      AL_POC19_Y	 +
      AL_POEP_Y	 +
      AL_PRDM_Y	 +
      AL_P_ESTINC_CHMI	 +
      AL_RABIGTLL_Y	 +
      AL_RACE_B_Af	 +
      AL_RACE_H_His	 +
      AL_RACE_OTHR	 +
      AL_RACE_W_Cau	 +
      AL_RACHILD_Y	 +
      AL_RAGEN_Y	 +
      AL_RAMEN_Y	 +
      AL_RANOGEN_Y	 +
      AL_RAPETITE_Y	 +
      AL_RAPLUS_Y	 +
      AL_RARTS_Y	 +
      AL_RAUTO_Y	 +
      AL_RAWOMEN_Y	 +
      AL_RBEAUTY_Y	 +
      AL_RBOOKS_Y	 +
      AL_RCHILDPR_Y	 +
      AL_RCOLLECT_Y	 +
      AL_RCOMPHMO_Y	 +
      AL_RC_M	 +
      AL_RC_Y	 +
      AL_RDOLLARS	 +
      AL_RELECTNC_Y	 +
      AL_REL_C_Cath	 +
      AL_REL_OTHR	 +
      AL_REL_P	 +
      AL_REL_S_Shin	 +
      AL_RETAIL_BUYER	 +
      AL_RETAIL_Y	 +
      AL_RETMILSP_Y	 +
      AL_RETMILT_Y	 +
      AL_RET_Y	 +
      AL_RFOOD_Y	 +
      AL_RFURNITR_Y	 +
      AL_RGARDEN_Y	 +
      AL_RGIFT_Y	 +
      AL_RHEALTH_Y	 +
      AL_RHMCARE_Y	 +
      AL_RHMFURN_Y	 +
      AL_RHOLIDAY_Y	 +
      AL_RHSWARE_Y	 +
      AL_RJEWELRY_Y	 +
      AL_RLINENS_Y	 +
      AL_RNOVEL_Y	 +
      AL_RORDERDT_D	 +
      AL_RORDERS	 +
      AL_ROTHER_Y	 +
      AL_RPERCARE_Y	 +
      AL_RPHOTO_Y	 +
      AL_RSPECFD_Y	 +
      AL_RSPECGFT_Y	 +
      AL_RSPORTS_Y	 +
      AL_RSTATION_Y	 +
      AL_RTRAVEL_Y	 +
      AL_Rank_21	 +
      AL_Rank_11p	 +
      AL_Rank_14n	 +
      AL_Rank_15n	 +
      AL_Rank_17n	 +
      AL_Rank_20n	 +
      AL_Rank_21n	 +
      AL_Rank_2p	 +
      AL_Rank_5n	 +
      AL_Rank_6n	 +
      AL_Rank_8p	 +
      AL_Rank_9n	 +
      AL_Rank_9p	 +
      AL_SGDI_Y	 +
      AL_SGFA_Y	 +
      AL_SGHL_Y	 +
      AL_SGLL_Y	 +
      AL_SGOE_Y	 +
      AL_SGPA_Y	 +
      AL_SGSE_Y	 +
      AL_SGTC_Y	 +
      AL_SGUP_Y	 +
      AL_SNOW_Y	 +
      AL_SOHOHH_Y	 +
      AL_SOHOIN_Y	 +
      AL_SPEA_Y	 +
      AL_SPEC_Y	 +
      AL_SPGD_Y	 +
      AL_SRET_Y	 +
      AL_TRAD	 +
      AL_TRVL_Y	 +
      AL_TUOCS_A001_Acc	 +
      AL_TUOCS_A264_SelfEm	 +
      AL_TUOCS_D173_Manag	 +
      AL_TUOCS_E149_InsurAg	 +
      AL_TUOCS_E250_Realtor	 +
      AL_TUOCS_E257_Sales	 +
      AL_TUOCS_F157_Labor	 +
      AL_TUOCS_G228_Pharm	 +
      AL_TUOCS_I143_HomeM	 +
      AL_TUOCS_M209_Nurse	 +
      AL_TUOCS_OTHR	 +
      AL_TUOC_A001_Acc	 +
      AL_TUOC_A264_SelfE	 +
      AL_TUOC_D173_Manag	 +
      AL_TUOC_E149_InsurAg	 +
      AL_TUOC_E250_Realtor	 +
      AL_TUOC_E257_Sales	 +
      AL_TUOC_F157_Labor	 +
      AL_TUOC_I143_HomeM	 +
      AL_TUOC_M209_Nurse	 +
      AL_TUOC_OTHR	 +
      AL_TVMA_Y	 +
      AL_VETERAN_Y	 +
      AL_VOTE_Y	 +
      AL_ZHIP19rnk	 +
      AL_age60_64	 +
      AL_r10_CBLU	 +
      AL_r10_CEBI	 +
      AL_r10_CSAG	 +
      AL_r10_CWHT	 +
      AL_r10_N2MOB	 +
      AL_r10_N2PHI	 +
      AL_r10_N2PMI	 +
      AL_r10_N2PWH	
    ,
    distribution = "gaussian",
    data = lg_mbrlvl_train,
    n.trees = 5,
    interaction.depth = 10,
    n.minobsinnode = 1000,
    shrinkage = 0.01,
    bag.fraction = 0.5,
    train.fraction = 1.0,
    cv.folds=0,
    keep.data = FALSE)

#write.csv(summary(gbm_model), "var_impv2.csv")

  