# 
# library(gbm)
# setwd("C:/Users/bpk3381/Documents/LGRiskAssessPhaseIIModeling/CustLevelModeling")
# 
# 
# cust_train_data  <-  read.csv("CUST_LVL_ROLLUP_S4_TRAIN.csv", 
#                         header = T, sep = ',');
# 
# 
# 
# cust_train_data  <- cust_train_data[which(!is.na(cust_train_data$log_Resid_RS_pspm_m)), ]
# 
# dim(cust_train_data)


gbm_model <- gbm(log_Resid_RS_pspm_m ~ 
db_CURRENT_D_B_RATING
+db_HISTORY_INDICATOR
+db_CONDITION_INDICATOR
+db_FINANCING_INDICATOR
+db_COMPANY_MOVED_INDICATOR
+db_FIRE_OCCURRED_INDICATOR
+db_TOTAL_SALES
+db_NET_WORTH
+db_STATEMENT_INDICATOR
+db_STATEMEMT_TYPE
+db_NUMBER_REGULAR_INQUIRES
+db_CURRENT_PAYDEX_MONTH_01
+db_PRIOR_PAYDEX_MONTH_02
+db_PRIOR_PAYDEX_MONTH_03
+db_PRIOR_PAYDEX_MONTH_04
+db_PRIOR_PAYDEX_MONTH_05
+db_PRIOR_PAYDEX_MONTH_06
+db_PRIOR_PAYDEX_MONTH_07
+db_PRIOR_PAYDEX_MONTH_08
+db_PRIOR_PAYDEX_MONTH_09
+db_PRIOR_PAYDEX_MONTH_10
+db_PRIOR_PAYDEX_MONTH_11
+db_PRIOR_PAYDEX_MONTH_12
+db_PRIOR_PAYDEX_MONTH_13
+db_PRIOR_PAYDEX_MONTH_14
+db_PRIOR_PAYDEX_MONTH_15
+db_PRIOR_PAYDEX_MONTH_16
+db_PRIOR_PAYDEX_MONTH_17
+db_PRIOR_PAYDEX_MONTH_18
+db_PRIOR_PAYDEX_MONTH_19
+db_PRIOR_PAYDEX_MONTH_20
+db_PRIOR_PAYDEX_MONTH_21
+db_PRIOR_PAYDEX_MONTH_22
+db_PRIOR_PAYDEX_MONTH_23
+db_PRIOR_PAYDEX_MONTH_24
+db_AVERAGE_HIGH_CREDIT
+db_MAXIMUM_HIGH_CREDIT
+db_NMBR_PAYMENT_EXPERIENCES
+db_NMBR_PAYMNT_EXPS_FOR_PAYDEX
+db_NMBR_SLOW_PAYMENTS
+db_NMBR_NEGATIVE_PAYMENTS
+db_nmbr_negative_and_slow_pymts
+db_NMBR_SATISFACTORY_PAYMENTS
+db_NMBR_PAYMENTS_PAST_DUE
+db_TOTAL_AMOUNT_PAST_DUE
+db_nmbr_pymts_30_days_past_due
+db_nmbr_pymts_60_days_past_due
+db_nmbr_pymts_90_days_past_due
+db_nmbr_pymts_120_days_past_due
+db_nmbr_pymts_180_days_past_due
+db_AMOUNT_OWED_30_DAYS
+db_NMBR_PAYMENT_REFERENCES
+db_YEAR_BUSINESS_STARTED
+db_legal_structure_company_type
+db_PRIMARY_SIC
+db_SECONDARY_SIC_1
+db_SECONDARY_SIC_2
+db_SECONDARY_SIC_3
+db_SECONDARY_SIC_4
+db_SECONDARY_SIC_5
+db_FACILITY_OWNED
+db_FACILITY_RENTED
+db_OPERATES_FROM_RESIDENCE
+db_BANKRUPTCY_INDICATOR
+db_BANKRUPTCY_DATE
+db_TOTAL_NMBR_LIENS
+db_TOTAL_NMBR_SUITS
+db_TOTAL_NMBR_JUDGMENTS
+db_TOTAL_NMBR_UCC_FILINGS
+db_G9_COMM_CRED_SCR_CLASS
+db_G9_COMM_CRED_SCR_PRCENT
+db_G9_COMM_CRED_SCR_POINTS
+db_G7_1_FNCL_STRESS_SCR_CLASS
+db_G7_1_FNCL_STRESS_SCR_PERCNT
+db_G7_1_INDUSTRY_PAYDEX_NORM
+db_G7_1_FNCL_STRESS_SCR_POINTS
+db_BD_IND
+db_DATE_BD
+db_IMPORT
+db_PUBPVT
+db_LOC_IND
+db_FBASEDAT
+db_DSUITS
+db_DJUDGMNT
+db_DLIENS
+db_CORPTYPE
+db_PEX_SL1
+db_PEX_NG1
+db_PEX_SN1
+db_PEXSAT1
+db_PEXCUR1
+db_PEX30X1
+db_PEX60X1
+db_PEX90X1
+db_PEX1201
+db_PEX1801
+db_PEX9991
+db_PEXOTH1
+db_PEXNPM1
+db_PEX_PM1
+db_TOTDOLL1
+db_SLODOLL1
+db_NEGDOLL1
+db_SN_DOLL1
+db_SATDOLL1
+db_DOLLCUR1
+db_DOLL_301
+db_DOLL_601
+db_DOLL_901
+db_DOLL_1201
+db_DOLL_1801
+db_DOLL_9991
+db_DOLLOTH1
+db_DOLLNPM1
+db_DOLL_PM1, 
distribution= 'gaussian', 
data = cust_train_data, 
n.trees = 500, 
bag.fraction = 0.5)



summary(gbm_model)
