###zip code level model;
###response: average risk score by zip;
##predictors: 1.) zip_aggregated amerilink variables; 2.) county health index variablesdownloaded from http://www.countyhealthrankings.org



# 
library(splines)
library(earth)
setwd("R:/SmallGroup/Analytics/New Case Underwriting Data Enhancement/Phase 2/MorbidityModel/MbrLvlModeling")


terr_data  <-  read.csv("R:/SmallGroup/Analytics/New Case Underwriting Data Enhancement/Phase 2/MorbidityModel/MbrLvlModeling/TERR_DATA_OUT.csv", 
                                 header = T, sep = ',');

dim(terr_data)
write.csv(names(terr_data), "terr_data_names.csv")
column_names  <-  names(terr_data)

names(terr_data)

library(randomForest)

rf_model <- randomForest(formula = zp_devel_member_final_score ~
                           zp_member_count  +
                           ZP_AGEINMTHS	+
                           ZP_APT_A	+
                           ZP_APT_B	+
                           ZP_APT_C	+
                           ZP_APT_N	+
                           ZP_APT_P	+
                           ZP_APT_S	+
                           ZP_APT_T	+
                           ZP_ATV_Y	+
                           ZP_Age_ge_65	+
                           ZP_BAVGDOLL	+
                           ZP_BAVGOFDL	+
                           ZP_BAVGONDL	+
                           ZP_BBDN_Y	+
                           ZP_BC_M	+
                           ZP_BC_Y	+
                           ZP_BHGHSCAL	+
                           ZP_BLOWSCAL	+
                           ZP_BMIDSCAL	+
                           ZP_BOAT_Y	+
                           ZP_BOFDOLLR	+
                           ZP_BOFORDER	+
                           ZP_BONDOLLR	+
                           ZP_BONORDER	+
                           ZP_BTOTLDOL	+
                           ZP_BTOTLORD	+
                           ZP_BUYER_Y	+
                           ZP_C210APVT	+
                           ZP_C210B200	+
                           ZP_C210BPVT	+
                           ZP_C210M200	+
                           ZP_CALAGE_rc	+
                           ZP_CAT_BUYER	+
                           ZP_CBLU	+
                           ZP_CBSA	+
                           ZP_CCIP	+
                           ZP_CCW_Y	+
                           ZP_CEBI	+
                           ZP_CE_Y	+
                           ZP_CFCC_F2	+
                           ZP_CFCC_F3	+
                           ZP_CFCC_F4	+
                           ZP_CFCC_F5	+
                           ZP_CFCC_F6	+
                           ZP_CFCC_G1	+
                           ZP_CFCC_G4	+
                           ZP_CFCC_G5	+
                           ZP_CFCC_G6	+
                           ZP_CFCC_N1	+
                           ZP_CFCC_N2	+
                           ZP_CGQS	+
                           ZP_CHMI	+
                           ZP_CHVA	+
                           ZP_CMYS_2	+
                           ZP_CMYS_3	+
                           ZP_CMYS_4	+
                           ZP_CMYS_5	+
                           ZP_CMYS_6	+
                           ZP_COLLEGE_Y	+
                           ZP_CONSHOP_Y	+
                           ZP_CO_Y	+
                           ZP_CPDC	+
                           ZP_CP_F	+
                           ZP_CP_M	+
                           ZP_CSAG_rc	+
                           ZP_CSR_Y	+
                           ZP_CWHT	+
                           ZP_DART_Y	+
                           ZP_DAUT_Y	+
                           ZP_DBBL_Y	+
                           ZP_DBIC_Y	+
                           ZP_DBKR_Y	+
                           ZP_DBOT_Y	+
                           ZP_DBVD_Y	+
                           ZP_DCAT_Y	+
                           ZP_DCDP_Y	+
                           ZP_DCHR_Y	+
                           ZP_DCMP_Y	+
                           ZP_DCOL_Y	+
                           ZP_DCRF_Y	+
                           ZP_DCRR_Y	+
                           ZP_DCTV_Y	+
                           ZP_DCUL_Y	+
                           ZP_DCUR_Y	+
                           ZP_DCVC_Y	+
                           ZP_DDOG_Y	+
                           ZP_DDWC_Y	+
                           ZP_DEID_10_Ir	+
                           ZP_DEID_16_Scot	+
                           ZP_DEID_58_AFRAm	+
                           ZP_DEID_6_EngBrit	+
                           ZP_DEID_8_Ger	+
                           ZP_DEID_9_His	+
                           ZP_DELE_Y	+
                           ZP_DFAS_Y	+
                           ZP_DFIT_Y	+
                           ZP_DFRN_Y	+
                           ZP_DFSH_Y	+
                           ZP_DFTV_Y	+
                           ZP_DGAR_Y	+
                           ZP_DGCH_Y	+
                           ZP_DGLF_Y	+
                           ZP_DGMB_Y	+
                           ZP_DGRM_Y	+
                           ZP_DHER_Y	+
                           ZP_DHH_Y	+
                           ZP_DHLH_Y	+
                           ZP_DHNT_Y	+
                           ZP_DHPC_Y	+
                           ZP_DHPL_Y	+
                           ZP_DIMP_Y	+
                           ZP_DMBY_Y	+
                           ZP_DMCI_Y	+
                           ZP_DMNY_Y	+
                           ZP_DMVT_Y	+
                           ZP_DNDL_Y	+
                           ZP_DNRM	+
                           ZP_DNRM_1	+
                           ZP_DNRM_2	+
                           ZP_DNRM_3	+
                           ZP_DNRM_4	+
                           ZP_DNRM_5	+
                           ZP_DNRM_6	+
                           ZP_DNRM_7	+
                           ZP_DNRM_8	+
                           ZP_DNRM_9	+
                           ZP_DNRM_10	+
                           ZP_DN_M	+
                           ZP_DN_Y	+
                           ZP_DPBT_Y	+
                           ZP_DPET_Y	+
                           ZP_DPIC_Y	+
                           ZP_DRCD_Y	+
                           ZP_DRES_Y	+
                           ZP_DRUN_Y	+
                           ZP_DRVL_Y	+
                           ZP_DSCC_Y	+
                           ZP_DSEW_Y	+
                           ZP_DSFN_Y	+
                           ZP_DSSK_Y	+
                           ZP_DSTK_Y	+
                           ZP_DSTV_Y	+
                           ZP_DSWP_Y	+
                           ZP_DTEC_Y	+
                           ZP_DTEN_Y	+
                           ZP_DTVL_Y	+
                           ZP_DUALINCM	+
                           ZP_DUALINCM_0	+
                           ZP_DUALINCM_1	+
                           ZP_DUALINCM_2	+
                           ZP_DUALINCM_3	+
                           ZP_DUALINCM_4	+
                           ZP_DUALINCM_5	+
                           ZP_DUALINCM_6	+
                           ZP_DUALINCM_7	+
                           ZP_DUALINCM_8	+
                           ZP_DUALINCM_9	+
                           ZP_DVDG_Y	+
                           ZP_DVDR_Y	+
                           ZP_DWELLING_AGE	+
                           ZP_DWIN_Y	+
                           ZP_DWKS_Y	+
                           ZP_DWLD_Y	+
                           ZP_DWLK_Y	+
                           ZP_DaysSinceLastOnLineOrder	+
                           ZP_DaysSinceLastRetailOrder	+
                           ZP_DaysSinceLastOffLineOrder	+
                           ZP_EMDM_Y	+
                           ZP_ESTINC19_A	+
                           ZP_ESTINC19_B	+
                           ZP_ESTINC19_C	+
                           ZP_ESTINC19_D	+
                           ZP_ESTINC19_E	+
                           ZP_ESTINC19_F	+
                           ZP_ESTINC19_G	+
                           ZP_ESTINC19_H	+
                           ZP_ESTINC19_I	+
                           ZP_ESTINC19_J	+
                           ZP_ESTINC19_K	+
                           ZP_ESTINC19_L	+
                           ZP_ESTINC19_M	+
                           ZP_ESTINC19_N	+
                           ZP_ESTINC19_O	+
                           ZP_ESTINC19_RC	+
                           ZP_FAMP_B	+
                           ZP_FAMP_C	+
                           ZP_FAMP_F	+
                           ZP_FAMP_G	+
                           ZP_FAMP_H	+
                           ZP_FAMP_M	+
                           ZP_FAMP_P	+
                           ZP_FAMP_S	+
                           ZP_FAMP_W	+
                           ZP_FINB_Y	+
                           ZP_FINC_Y	+
                           ZP_FINI_Y	+
                           ZP_FURN_Y	+
                           ZP_GEND_F	+
                           ZP_GEND_M	+
                           ZP_GENERS_01s_StrapS	+
                           ZP_GENERS_02s_RR	+
                           ZP_GENERS_03s_BloomB	+
                           ZP_GENERS_04s_RRent	+
                           ZP_GENERS_05s_MinM	+
                           ZP_GENERS_06s_InIntel	+
                           ZP_GENERS_07s_FamF	+
                           ZP_GENERS_09s_UUC	+
                           ZP_GENERS_10s_BB	+
                           ZP_GENERS_11l_STT	+
                           ZP_GENERS_12l_GnG	+
                           ZP_GENERS_13l_STS	+
                           ZP_GENERS_14l_MM	+
                           ZP_GENERS_15l_AmB	+
                           ZP_GENERS_16l_UMix	+
                           ZP_GENERS_17l_UrbanB	+
                           ZP_GENERS_18l_CreditC	+
                           ZP_GENERS_19l_BCS	+
                           ZP_GENERS_20l_SettS	+
                           ZP_GENERS_21l_ClassR	+
                           ZP_GENERS_22l_AllAmO	+
                           ZP_GENERS_23t_RuralO	+
                           ZP_GENERS_24t_FamTran	+
                           ZP_GENERS_25t_UrOut	+
                           ZP_GENERS_26t_SubM	+
                           ZP_GENERS_27t_MInf	+
                           ZP_GENERS_28t_WW	+
                           ZP_GENERS_29t_USoph	+
                           ZP_GENERS_30t_SubStr	+
                           ZP_GENERS_31t_ENC	+
                           ZP_GENERS_32t_AFUC	+
                           ZP_GENERS_33t_BCB	+
                           ZP_GENERS_34t_UStrug	+
                           ZP_GENERS_35x_LExtFam	+
                           ZP_GENERS_36x_UrbSing	+
                           ZP_GENERS_37x_EstSettIn	+
                           ZP_GENERS_38x_RuralBMIt	+
                           ZP_GENERS_39x_MWChD	+
                           ZP_GENERS_40x_StrugSub	+
                           ZP_GENERS_41x_EthDUrB	+
                           ZP_GENERS_42x_MovStC	+
                           ZP_GENERS_43x_BigBBC	+
                           ZP_GENERS_44y_ESecCSt	+
                           ZP_GENERS_45y_YSMob	+
                           ZP_GENERS_46y_SupHSD	+
                           ZP_GENERS_47y_StUpsC	+
                           ZP_GENERS_48y_ParGo	+
                           ZP_GENERS_49y_LOffMD	+
                           ZP_GENERS_50y_ChrRes	+
                           ZP_GENERS_51y_YSinglCY	+
                           ZP_GENERS_52y_FamFirst	+
                           ZP_HHCOMP_A	+
                           ZP_HHCOMP_B	+
                           ZP_HHCOMP_C	+
                           ZP_HHCOMP_D	+
                           ZP_HHCOMP_E	+
                           ZP_HHCOMP_F	+
                           ZP_HHCOMP_G	+
                           ZP_HHCOMP_H	+
                           ZP_HHCOMP_I	+
                           ZP_HHCOMP_J	+
                           ZP_HHCOMP_K	+
                           ZP_HHCOMP_L	+
                           ZP_HIRI	+
                           ZP_HIRI_0	+
                           ZP_HIRI_1	+
                           ZP_HIRI_2	+
                           ZP_HIRI_3	+
                           ZP_HIRI_4	+
                           ZP_HIRI_5	+
                           ZP_HIRI_6	+
                           ZP_HIRI_7	+
                           ZP_HIRI_8	+
                           ZP_HIRI_9	+
                           ZP_HIR_Y	+
                           ZP_HOMI_Y	+
                           ZP_HOMO_Y	+
                           ZP_HOMSTAT_P	+
                           ZP_HOMSTAT_R	+
                           ZP_HOMSTAT_T	+
                           ZP_HOMSTAT_U	+
                           ZP_HOMSTAT_Y	+
                           ZP_HOPLUS_P	+
                           ZP_HOPLUS_Y	+
                           ZP_HTFH_Y	+
                           ZP_HVZIP4	+
                           ZP_IDC_Y	+
                           ZP_ILOR	+
                           ZP_INAH	+
                           ZP_INPH	+
                           ZP_IOHO_Y	+
                           ZP_IOLA_Y	+
                           ZP_IOLP_Y	+
                           ZP_IOMA_Y	+
                           ZP_IOMG_Y	+
                           ZP_IOOW_Y	+
                           ZP_IOPT_Y	+
                           ZP_IORE_Y	+
                           ZP_IOSA_Y	+
                           ZP_IOSE_Y	+
                           ZP_IOST_Y	+
                           ZP_IOTR_Y	+
                           ZP_IPAE_Y	+
                           ZP_IPDI_Y	+
                           ZP_IPOT_Y	+
                           ZP_IPSR_Y	+
                           ZP_IPVM_Y	+
                           ZP_IRAE_Y	+
                           ZP_IRDI_Y	+
                           ZP_IROT_Y	+
                           ZP_IRSR_Y	+
                           ZP_IRVM_Y	+
                           ZP_IncPerAdult	+
                           ZP_LAAI_Y	+
                           ZP_LAAM_Y	+
                           ZP_LAAR_Y	+
                           ZP_LAAS_Y	+
                           ZP_LABE_Y	+
                           ZP_LACE_Y	+
                           ZP_LACN_Y	+
                           ZP_LACO_Y	+
                           ZP_LADY_Y	+
                           ZP_LAEA_Y	+
                           ZP_LAFF_Y	+
                           ZP_LAFT_Y	+
                           ZP_LAIN_Y	+
                           ZP_LAIS_Y	+
                           ZP_LANG_6_English	+
                           ZP_LANG_9_HisSp	+
                           ZP_LANL_Y	+
                           ZP_LAOP_Y	+
                           ZP_LAOR_Y	+
                           ZP_LAPL_Y	+
                           ZP_LARO_Y	+
                           ZP_LART_Y	+
                           ZP_LASF_Y	+
                           ZP_LASI_Y	+
                           ZP_LASO_Y	+
                           ZP_LASS_Y	+
                           ZP_LAT	+
                           ZP_LATL_Y	+
                           ZP_LATR_Y	+
                           ZP_LATS_Y	+
                           ZP_LAYC_Y	+
                           ZP_LNG	+
                           ZP_LOWD_Y	+
                           ZP_LWCM02	+
                           ZP_LWCM03	+
                           ZP_LWCM04	+
                           ZP_LWCM05	+
                           ZP_LWCM06	+
                           ZP_LWCM07	+
                           ZP_LWCM08	+
                           ZP_LWCM09	+
                           ZP_LWCM10	+
                           ZP_LWCM11	+
                           ZP_LWCM12	+
                           ZP_LWCM02rrnk	+
                           ZP_LWCM03rrnk	+
                           ZP_LWCM04rrnk	+
                           ZP_LWCM05rrnk	+
                           ZP_LWCM06rrnk	+
                           ZP_LWCM07rrnk	+
                           ZP_LWCM08rrnk	+
                           ZP_LWCM09rrnk	+
                           ZP_LWCM10rrnk	+
                           ZP_LWCM11rrnk	+
                           ZP_LWCM12rrnk	+
                           ZP_LiveWell_1	+
                           ZP_LiveWell_2	+
                           ZP_LiveWell_3	+
                           ZP_LiveWell_4	+
                           ZP_LiveWell_5	+
                           ZP_LiveWell_6	+
                           ZP_MB2G_1_Express	+
                           ZP_MB2G_2_Driven	+
                           ZP_MB2G_3_ACap	+
                           ZP_MB2G_4_RS	+
                           ZP_MB2G_5_DTE	+
                           ZP_MB2G_6_Soph	+
                           ZP_MB2G_7_MT	+
                           ZP_MB2G_8_Dev	+
                           ZP_MB2S_10_RSRel	+
                           ZP_MB2S_11_RSRig	+
                           ZP_MB2S_12_RSRes	+
                           ZP_MB2S_13_DTEDet	+
                           ZP_MB2S_14_DTEDis	+
                           ZP_MB2S_15_DTEDar	+
                           ZP_MB2S_16_SSD	+
                           ZP_MB2S_17_SSy	+
                           ZP_MB2S_18_SSyn	+
                           ZP_MB2S_19_MTwM	+
                           ZP_MB2S_1_ExElus	+
                           ZP_MB2S_20_MTwMet	+
                           ZP_MB2S_21_MTwMot	+
                           ZP_MB2S_22_DDis	+
                           ZP_MB2S_23_DDisc	+
                           ZP_MB2S_24_DDeft	+
                           ZP_MB2S_2_ExEval	+
                           ZP_MB2S_3_ExExub	+
                           ZP_MB2S_4_DDel	+
                           ZP_MB2S_5_DDil	+
                           ZP_MB2S_6_DDy	+
                           ZP_MB2S_7_ACA	+
                           ZP_MB2S_8_ACApp	+
                           ZP_MB2S_9_ACAtt	+
                           ZP_MEDA	+
                           ZP_MEMW_Y	+
                           ZP_MISC_Y	+
                           ZP_MOBPLUS_M	+
                           ZP_MOBPLUS_P	+
                           ZP_MOBPLUS_S	+
                           ZP_MORI_Y	+
                           ZP_MR_M	+
                           ZP_MR_Y	+
                           ZP_MSR_Y	+
                           ZP_M_CHMI	+
                           ZP_N1819_Y	+
                           ZP_N2029_Y	+
                           ZP_N2AUTO	+
                           ZP_N2MAH	+
                           ZP_N2MOB	+
                           ZP_N2NCY_A	+
                           ZP_N2NCY_B	+
                           ZP_N2NCY_C	+
                           ZP_N2NCY_D	+
                           ZP_N2PBL	+
                           ZP_N2PDV	+
                           ZP_N2PHI	+
                           ZP_N2PMI	+
                           ZP_N2PMR	+
                           ZP_N2PMV	+
                           ZP_N2POO	+
                           ZP_N2PSB	+
                           ZP_N2PSU	+
                           ZP_N2PWC	+
                           ZP_N2PWH	+
                           ZP_N3039_Y	+
                           ZP_N4049_Y	+
                           ZP_N5059_Y	+
                           ZP_N6064_Y	+
                           ZP_N65P_Y	+
                           ZP_NAH19	+
                           ZP_NDAD_Y	+
                           ZP_NDBD_Y	+
                           ZP_NDCD_Y	+
                           ZP_NDDD_Y	+
                           ZP_NDFD_Y	+
                           ZP_NDGD_Y	+
                           ZP_NDOD_Y	+
                           ZP_NDYD_Y	+
                           ZP_NETW19_A	+
                           ZP_NETW19_B	+
                           ZP_NETW19_C	+
                           ZP_NETW19_D	+
                           ZP_NETW19_E	+
                           ZP_NETW19_F	+
                           ZP_NETW19_G	+
                           ZP_NETW19_H	+
                           ZP_NETW19_I	+
                           ZP_NETW19_J	+
                           ZP_NETW19_K	+
                           ZP_NETW19_L	+
                           ZP_NETW19_M	+
                           ZP_NETW19_N	+
                           ZP_NETW19_RC	+
                           ZP_NOC	+
                           ZP_NOC19	+
                           ZP_NPH19	+
                           ZP_NTWPERYR	+
                           ZP_NWPerAdult	+
                           ZP_OABIGTLL_Y	+
                           ZP_OACHILD_Y	+
                           ZP_OAGEN_Y	+
                           ZP_OAMEN_Y	+
                           ZP_OANOGEN_Y	+
                           ZP_OAPETITE_Y	+
                           ZP_OAPLUS_Y	+
                           ZP_OARTS_Y	+
                           ZP_OATEEN_Y	+
                           ZP_OAUTO_Y	+
                           ZP_OAWOMEN_Y	+
                           ZP_OBEAUTY_Y	+
                           ZP_OBOOKS_Y	+
                           ZP_OCHILDPR_Y	+
                           ZP_OCOLLECT_Y	+
                           ZP_OCOMPHMO_Y	+
                           ZP_OCRAFTS_Y	+
                           ZP_OC_10_PTec	+
                           ZP_OC_13_Teach	+
                           ZP_OC_20_Adm	+
                           ZP_OC_21_Manag	+
                           ZP_OC_22_Propr	+
                           ZP_OC_30_Sales	+
                           ZP_OC_40_Cler	+
                           ZP_OC_50_Craft	+
                           ZP_OC_52_Oper	+
                           ZP_OC_61_UNSK	+
                           ZP_OC_62_SerW	+
                           ZP_OC_70_Mil	+
                           ZP_OC_80_Stud	+
                           ZP_OC_90_Ret	+
                           ZP_OC_91_HWf	+
                           ZP_OC_93_NCD	+
                           ZP_OELECTNC_Y	+
                           ZP_OFFLINE_BUYER	+
                           ZP_OFOOD_Y	+
                           ZP_OFURNITR_Y	+
                           ZP_OGARDEN_Y	+
                           ZP_OGEN_Y	+
                           ZP_OGIFT_Y	+
                           ZP_OHEALTH_Y	+
                           ZP_OHMCARE_Y	+
                           ZP_OHMFURN_Y	+
                           ZP_OHOLIDAY_Y	+
                           ZP_OHSWARE_Y	+
                           ZP_OILC_Y	+
                           ZP_OJEWELRY_Y	+
                           ZP_OLINENS_Y	+
                           ZP_OMUSIC_Y	+
                           ZP_ONLA_Y	+
                           ZP_ONLINE_BUYER	+
                           ZP_ONOVEL_Y	+
                           ZP_OOTHER_Y	+
                           ZP_OPERCARE_Y	+
                           ZP_OPETS_Y	+
                           ZP_OPHOTO_Y	+
                           ZP_OSPECFD_Y	+
                           ZP_OSPECGFT_Y	+
                           ZP_OSPORTS_Y	+
                           ZP_OSTATION_Y	+
                           ZP_OTRAVEL_Y	+
                           ZP_OVIDDVD_Y	+
                           ZP_PART_D	+
                           ZP_PART_I	+
                           ZP_PART_R	+
                           ZP_PDPE	+
                           ZP_PFFS	+
                           ZP_PILOTS_Y	+
                           ZP_POC19_P	+
                           ZP_POC19_Y	+
                           ZP_POEP_Y	+
                           ZP_PRDM_Y	+
                           ZP_P_ESTINC_CHMI	+
                           ZP_RABIGTLL_Y	+
                           ZP_RACE_B_Af	+
                           ZP_RACE_H_His	+
                           ZP_RACE_W_Cau	+
                           ZP_RACHILD_Y	+
                           ZP_RAGEN_Y	+
                           ZP_RAMEN_Y	+
                           ZP_RANOGEN_Y	+
                           ZP_RAPETITE_Y	+
                           ZP_RAPLUS_Y	+
                           ZP_RARTS_Y	+
                           ZP_RAUTO_Y	+
                           ZP_RAWOMEN_Y	+
                           ZP_RBEAUTY_Y	+
                           ZP_RBOOKS_Y	+
                           ZP_RCHILDPR_Y	+
                           ZP_RCOLLECT_Y	+
                           ZP_RCOMPHMO_Y	+
                           ZP_RC_M	+
                           ZP_RC_Y	+
                           ZP_RDOLLARS	+
                           ZP_RELECTNC_Y	+
                           ZP_REL_C_Cath	+
                           ZP_REL_P	+
                           ZP_REL_S_Shin	+
                           ZP_RETAIL_BUYER	+
                           ZP_RETAIL_Y	+
                           ZP_RETMILSP_Y	+
                           ZP_RETMILT_Y	+
                           ZP_RET_Y	+
                           ZP_RFOOD_Y	+
                           ZP_RFURNITR_Y	+
                           ZP_RGARDEN_Y	+
                           ZP_RGIFT_Y	+
                           ZP_RHEALTH_Y	+
                           ZP_RHMCARE_Y	+
                           ZP_RHMFURN_Y	+
                           ZP_RHOLIDAY_Y	+
                           ZP_RHSWARE_Y	+
                           ZP_RJEWELRY_Y	+
                           ZP_RLINENS_Y	+
                           ZP_RNOVEL_Y	+
                           ZP_RORDERS	+
                           ZP_ROTHER_Y	+
                           ZP_RPERCARE_Y	+
                           ZP_RPHOTO_Y	+
                           ZP_RSPECFD_Y	+
                           ZP_RSPECGFT_Y	+
                           ZP_RSPORTS_Y	+
                           ZP_RSTATION_Y	+
                           ZP_RTRAVEL_Y	+
                           ZP_Rank_21	+
                           ZP_Rank_11p	+
                           ZP_Rank_14n	+
                           ZP_Rank_15n	+
                           ZP_Rank_17n	+
                           ZP_Rank_20n	+
                           ZP_Rank_21n	+
                           ZP_Rank_2p	+
                           ZP_Rank_5n	+
                           ZP_Rank_6n	+
                           ZP_Rank_8p	+
                           ZP_Rank_9n	+
                           ZP_Rank_9p	+
                           ZP_SGDI_Y	+
                           ZP_SGFA_Y	+
                           ZP_SGHL_Y	+
                           ZP_SGLL_Y	+
                           ZP_SGOE_Y	+
                           ZP_SGPA_Y	+
                           ZP_SGSE_Y	+
                           ZP_SGTC_Y	+
                           ZP_SGUP_Y	+
                           ZP_SNOW_Y	+
                           ZP_SOHOHH_Y	+
                           ZP_SOHOIN_Y	+
                           ZP_SPEA_Y	+
                           ZP_SPEC_Y	+
                           ZP_SPGD_Y	+
                           ZP_SRET_Y	+
                           ZP_TRAD	+
                           ZP_TRVL_Y	+
                           ZP_TUOCS_A001_Acc	+
                           ZP_TUOCS_A264_SelfEm	+
                           ZP_TUOCS_D173_Manag	+
                           ZP_TUOCS_E149_InsurAg	+
                           ZP_TUOCS_E250_Realtor	+
                           ZP_TUOCS_E257_Sales	+
                           ZP_TUOCS_F157_Labor	+
                           ZP_TUOCS_G228_Pharm	+
                           ZP_TUOCS_I143_HomeM	+
                           ZP_TUOCS_M209_Nurse	+
                           ZP_TUOC_A001_Acc	+
                           ZP_TUOC_A264_SelfE	+
                           ZP_TUOC_D173_Manag	+
                           ZP_TUOC_E149_InsurAg	+
                           ZP_TUOC_E250_Realtor	+
                           ZP_TUOC_E257_Sales	+
                           ZP_TUOC_F157_Labor	+
                           ZP_TUOC_I143_HomeM	+
                           ZP_TUOC_M209_Nurse	+
                           ZP_TVMA_Y	+
                           ZP_VETERAN_Y	+
                           ZP_VOTE_Y	+
                           ZP_ZHIP19rnk	+
                           zp_rorderdt_d	
                         , 
                         data = terr_data  , 
                         imortance = TRUE,
                         proximity = TRUE,
                         na.action=na.roughfix, 
                         ntree = 500);

#save.image("rf_terr_factors.RData")
#load("rf_terr_factors.RData")

predicted <- predict(rf_model, terr_data)

importance <- data.frame(vars = rownames(rf_model$importance), importance = rf_model$importance)
head(importance)
importance <- importance[order(importance$IncNodePurity, decreasing = TRUE), ]
head(importance)

write.csv(importance[1:100,], "top_terr_vars.csv")
zip_healthscore <- data.frame(zip_cd = terr_data$subs_zip_cd, zip_health_score = predicted)
write.csv (zip_healthscore, "zip_healthscore.csv")
